In [1]:
import reduced_echelon
import numpy as np

# 1.2.5

In [14]:
# 1.2.5 Solve the linear system by Gaussian elimination

print("The augmented matrix of the system is:")
A = np.array([
    [1, 1, 2, 8],
    [-1, -2, 3, 1],
    [3, -7, 4, 10]
])
print(A)

print("Applying Gaussian elimination to A:") 
A = reduced_echelon.forward(A)
print(A)

The augmented matrix of the system is:
[[ 1  1  2  8]
 [-1 -2  3  1]
 [ 3 -7  4 10]]
Applying Gaussian elimination to A:
[[ 1  1  2  8]
 [ 0  1 -5 -9]
 [ 0  0  1  2]]


The corresponding system of the row echelon form of A is  
$\Bigg\{\begin{align*}x_1 + x_2 + 2x_3 &= 8\\x_2 - 5x_3 &= -9\\x_3 &= 2\\\end{align*}$

$\Rightarrow (x_1, x_2, x_3) = (3, 1, 2)$

## 1.2.15

In [2]:
print("The augmented matrix of the system is:")
A = np.array([
    [2, 1, 3, 0],
    [1, 2, 0, 0],
    [0, 1, 1, 0]
])
print(A)

print("The reduced row echelon form of the matrix is:")
print(reduced_echelon.backward(reduced_echelon.forward(A)))

The augmented matrix of the system is:
[[2 1 3 0]
 [1 2 0 0]
 [0 1 1 0]]
The reduced row echelon form of the matrix is:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


The corresponding system to the above augmented matrix is 

$\Bigg\{\begin{align*}x_1 &= 0\\x_2 &= 0\\x_3 &= 0\\\end{align*}$

## 1.2.19

In [3]:
print("The augmented matrix of the system is:")
A = np.array([
    [0, 2, 2, 4, 0],
    [1, 0, -1, -3, 0],
    [2, 3, 1, 1, 0],
    [-2, 1, 3, -2, 0]
])
print(A)

print("The reduced row echelon form of the matrix is:")
print(reduced_echelon.backward(reduced_echelon.forward(A)))

The augmented matrix of the system is:
[[ 0  2  2  4  0]
 [ 1  0 -1 -3  0]
 [ 2  3  1  1  0]
 [-2  1  3 -2  0]]
The reduced row echelon form of the matrix is:
[[ 1  0 -1  0  0]
 [ 0  1  1  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0  0]]


The corresponding system of the above reduced echelon form matrix is

$\Bigg\{\begin{align*}w -    y &= 0 \\ x + y &= 0 \\ z &= 0 \end{align*}$

Since only $w,x,z$ has leading 1 then $y$ is the free variable. 

Set $y = t, t \in \mathbb{R}$. We have $(w,x,y,z) = (t, -t, t, 0)$

## 1.2.31

In [7]:
A = np.array([
    [1, 3],
    [2, 7]
])
print ("A =")
print(A)
print("2 different row echelon forms of A are")
print(reduced_echelon.forward(A))
print("and")
print(np.array([
    [1, 4],
    [0, 1]
]))

A =
[[1 3]
 [2 7]]
2 different row echelon forms of A are
[[1 3]
 [0 1]]
and
[[1 4]
 [0 1]]


 ## True/False
 
 a) If a matrix is in reduced echelon form then it is also in row echelon form  
 This statement is **True** because it satisfies the following conditions:  
    + Every non-zero row has a leading 1
    + Zero rows are at the bottom
    + The leading 1 of the upper row is on the left of the leading 1 of the lower row
    
 b) If any elementary row operation is applied to a matrix that is in row echelon form, the resulting matrix will still be in row echelon form  
 This statement is **False** because if we multiply any row with a number not equal to 1, then that row no longer has the leading 1.
 
 c) Every matrix has a unique row echelon form  
 This statement is **False**. Take the previous matrix as an example: Matrix **A**

In [8]:
A = np.array([
    [1, 3],
    [2, 7]
])
print ("A =")
print(A)
print("has 2 different row echelon forms of A are")
print(reduced_echelon.forward(A))
print("and")
print(np.array([
    [1, 4],
    [0, 1]
]))

A =
[[1 3]
 [2 7]]
has 2 different row echelon forms of A are
[[1 3]
 [0 1]]
and
[[1 4]
 [0 1]]
