pseudocode:

Forward Step
1. Locate the leftmost non-zero column and call it A
2. Interchange the rows such that top entry of column A is not zero. Call it a
3. Multiply the top role by 1/a
4. Multiply the top row with a suitable numebr and addd it to other below rows so that all other elements of column A is 0
5. If there is a zero row, move it to the bottom
6. Ignore the top row and repeat the process with the next one

Backward Step
7. Beginning with the last nonzero row and working upward, add suitable multiples of each row to the rows above to introduce zeros above the leading 1’s

In [10]:
import numpy as np
np.set_printoptions(precision=3) # set numpy matrix display of floating point not exceed 3 decimal points

In [11]:
def forward_helper(A, row, column):
    """
    Recursive helper method for forward(A)
    """
    # base case
    if (row == len(A)):
#         print("\nDONE\n", A)
        return A
    else:
        # 5. move zero row to the last row of matrix
        if is_zero_row(A, row):
            if row == len(A) - 1:
                return A
            temp_row = len(A)-1
            while is_zero_row(A, temp_row):
                temp_row -= 1
            if temp_row == row:
                return A
            else:
                A = row_interchange(A, row, temp_row)
        # 1. locate the leftmost non-zero column
        while(is_zero_column(A, row, column)): # move to the next column if current column is zero-column
            column += 1
        if column == len(A[0]-1):
            return A
        for i in range(row, len(A)):
            if not A[i][column] == 0:
                A = row_interchange(A, row, i) # 2. interchange
                
#                 print(f"Interchange row {row} with row {i} \n", A)
                
                break
        # 3. multiply the top row by 1/a
        alpha = A[row][column]
        A = row_scalar_multiply(A, row, 1/alpha)
        
#         print(f"Multiply row {row} with 1/{alpha} \n", A)
        
        # 4. multiply the top row with a suitable number
        if not(row == len(A)-1):
            for i in range (row+1, len(A)):
                if not A[i][column] == 0:
                    alpha = A[i][column]
                    B = row_addition(row_scalar_multiply(A, row, -1*alpha), row, i)
                    A = row_scalar_multiply(B, row, -1/alpha)
                    
#             print(f"Multiply the row {row} with a suitable number and addd it to other", \
#             "below rows so that all other elements of the current column is 0 \n", A) 
            
        # 6. Recursion        
        return forward_helper(A, row+1, column+1)

In [20]:
def backward_helper(A, row):
    """
    Recursive helper method for backward(A)
    """
    # base case
    if row == 0:
        print("\nDONE\n", A)
        return A
    
    # recursive case
    if is_zero_row(A, row):
        return backward_helper(A, row-1)
    else:
        column = -1
        for i in range(len(A[0])):
            if A[row][i] == 1:
                column = i
                break
                
        for i in range(row-1, -1, -1):
            alpha = A[i][column]
            if not alpha == 0: # ignore 0 entry
                B = row_addition(row_scalar_multiply(A, row, -1*alpha), row, i)
                A = row_scalar_multiply(B, row, -1/alpha)
#         print(f"Row {row} \n", A)
        return backward_helper(A, row-1)

In [13]:
def forward(A):
    """
    Forward step of Gaussian-Jordan elimination
    @Param numpy matrix A
    @Return row echelon form of matrix A
    """
    return forward_helper(A,0,0)

def backward(A):
    """
    Backward step of Gaussian-Jordan elimination
    @Param echelon form of matrix A
    @Return reduced row echelon form of matrix A
    """
    return backward_helper(A, len(A)-1)

In [14]:
# Set of matrix row operation routines
def row_interchange(A, row1, row2):
    """
    Interchange 2 rows (row1 and row2) of matrix A
    @Return the updated matrix
    """
    A[[row1, row2]] = A[[row2, row1]]
    return A

def row_scalar_multiply(A, row, alpha):
    """
    Multiply all entries in row of matrix A with scalar alpha
    @Return the updated matrix
    """
    A[row] = A[row]*alpha
    return A
    
def row_addition(A, row1, row2):
    """
    Add entry-wisely row1 to row2 of matrix A
    @Return the updated matrix
    """
    A[row2] = A[row1] + A[row2]
    return A
    
def is_zero_row(A, row):
    """
    Check if row of matrix A is a zero-row. 
    @Return True if it is, False otherwise
    """
    return np.sum(A[row]**2) == 0

def is_zero_column(A, row, column):
    """
    Check if sub column below row of matrix A is a zero sub column
    @Return True if it is, False otherwise
    """
    return np.sum(A[row:,column]**2) == 0

In [15]:
# Test routines
A = [[0, 0, -2, 0, 7, 12, 0],
     [2, 4, 0, 6, 12, 28, 0],
     [2, 4, 0,6, -5, -1, 0],
     [0, 0, 0, 0, 0, 0, 0]]
A = np.array(A)

print("Original matrix")
print(A)
B = A.copy()
print("Interchange row 0 and row 1 \n", row_interchange(B, 0, 1))
B = A.copy()
print("Multiply row 1 with scalar 2 \n", row_scalar_multiply(B, 1, 2))
B = A.copy()
print("Add row 1 to row 2 \n", row_addition(B, 1, 2))

print(is_zero_row(A,-1))
print(is_zero_row(A,-2))
print(is_zero_column(A,1,2))
print(is_zero_column(A,0,0))

Original matrix
[[ 0  0 -2  0  7 12  0]
 [ 2  4  0  6 12 28  0]
 [ 2  4  0  6 -5 -1  0]
 [ 0  0  0  0  0  0  0]]
Interchange row 0 and row 1 
 [[ 2  4  0  6 12 28  0]
 [ 0  0 -2  0  7 12  0]
 [ 2  4  0  6 -5 -1  0]
 [ 0  0  0  0  0  0  0]]
Multiply row 1 with scalar 2 
 [[ 0  0 -2  0  7 12  0]
 [ 4  8  0 12 24 56  0]
 [ 2  4  0  6 -5 -1  0]
 [ 0  0  0  0  0  0  0]]
Add row 1 to row 2 
 [[ 0  0 -2  0  7 12  0]
 [ 2  4  0  6 12 28  0]
 [ 4  8  0 12  7 27  0]
 [ 0  0  0  0  0  0  0]]
True
False
True
False


In [16]:
A = [[1, 3, -2, 0, 2, 0, 0],
     [2, 6, -5,-2, 4, -3, -1],
     [0, 0, 5, 10, 0, 15, 5],
     [2, 6, 0, 8, 4, 18, 6]]
A = np.array(A, dtype = np.float64)
print("Gaussian-Jordan elimination on matrix\n", A)
print("\nFORWARD")
A = forward(A)
print("\nBACKWARD")
backward(A)

Gaussian-Jordan elimination on matrix
 [[ 1.  3. -2.  0.  2.  0.  0.]
 [ 2.  6. -5. -2.  4. -3. -1.]
 [ 0.  0.  5. 10.  0. 15.  5.]
 [ 2.  6.  0.  8.  4. 18.  6.]]

FORWARD

BACKWARD
Row 2 
 [[ 1.     3.    -2.     0.     2.     0.     0.   ]
 [-0.    -0.     1.     2.    -0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     1.     0.333]
 [ 0.     0.     0.     0.     0.     0.     0.   ]]
Row 1 
 [[ 1.     3.     0.     4.     2.     0.     0.   ]
 [-0.    -0.     1.     2.    -0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     1.     0.333]
 [ 0.     0.     0.     0.     0.     0.     0.   ]]

DONE
 [[ 1.     3.     0.     4.     2.     0.     0.   ]
 [-0.    -0.     1.     2.    -0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     1.     0.333]
 [ 0.     0.     0.     0.     0.     0.     0.   ]]


array([[ 1.   ,  3.   ,  0.   ,  4.   ,  2.   ,  0.   ,  0.   ],
       [-0.   , -0.   ,  1.   ,  2.   , -0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.333],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ]])

In [31]:
A = np.array([
    [1, -1, 2, 2],
    [0, 0, 1, 4],
    [0, 0, 0, 1]
])

backward(forward(A))


DONE
 [[ 1 -1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]]


array([[ 1, -1,  0,  0],
       [ 0,  0,  1,  0],
       [ 0,  0,  0,  1]])

In [18]:
def solve(A):
    if not is_consistent(A):
        return "No Solution"
    return None

In [35]:
def is_consistent(A):
    """
    Check if a system is consistent, i.e. has solution
    @Param matrix A
    @Return True if matrix A has solution. False otherwise
    """
    A = backward(forward(A))
    for i in range(len(A)-1, -1, -1):
        if not is_zero_row(A, i):
            if np.sum(A[i][:-1]**2) == 0:
                return False
            else:
                return True

def is_unique_solution(A):
    """
    Check if a system has unique solution
    @Param matrix A
    @Return True if matrix A has unique solution. False otherwise
    """
    if count_leading_one(A) == len(A[0] - 1):
        return True
    return False

def is_infinite_solution(A):
    """
    Check if a system has infinite solution
    @Param matrix A
    @Return True if matrix A has infinite solution. False otherwise
    """
    if count_leading_one(A) > len(A[0] - 1):
        return True
    return False
    
def remove_zero_row(A):
    """
    Remove the zero row (if there is) in a reduced echelon form of matrix A
    @Param matrix A
    @Return an updated matrix A with all zero rows removed
    """
    number_of_row = len(A)
    A = backward(forward(A))
    for i in range(len(A)-1, -1, -1):
        if is_zero_row(A,i):
            number_of_row -= 1
        else:
            break
    return A[:number_of_row]

def count_leading_one(A):
    """
    @Return the number of leading 1's
    """
    A = remove_zero_row(A)
    return len(A)
    
M = np.array([
    [1,-1,2,2],
    [0,1,-2,-4],
    [0,0,1,3]
])

N = np.array([
    [1,-1,2,2],
    [0,0,1,2],
    [0,0,0,0]
])

M = np.array([
    [1,-1,2,2],
    [0,0, 1,4],
    [0,0,0,1]
])

B = A.copy()
print(is_consistent(B))
B = A.copy()
print(is_unique_solution(B))
B = A.copy()
print(is_infinite_solution(B))
B = A.copy()
print(remove_zero_row(A))
B = A.copy()
print(count_leading_ont(A))


DONE
 [[ 1 -1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]]


False

In [37]:
from numpy.linalg import inv
a = np.array([
    [1, 2, 3],
    [2, 5, 3],
    [1, 0, 8]
])

inv(a)

array([[-40.,  16.,   9.],
       [ 13.,  -5.,  -3.],
       [  5.,  -2.,  -1.]])