pseudocode:

Forward Step
1. Locate the leftmost non-zero column and call it A
2. Interchange the rows such that top entry of column A is not zero. Call it a
3. Multiply the top role by 1/a
4. Multiply the top row with a suitable numebr and addd it to other below rows so that all other elements of column A is 0
5. If there is a zero row, move it to the bottom
6. Ignore the top row and repeat the process with the next one

Backward Step
7.

In [82]:
import numpy as np

In [132]:
def forward(A, row, column):
    """
    Forward step of Gaussian-Jordan elimination
    Return row echelon form of matrix A
    """
    # base case
    if (row == len(A)):
        print("\nDONE\n", A)
        return A
    else:
        # 5. move zero row to the last row of matrix
        if is_zero_row(A, row):
            temp_row = len(A-1)
            while is_zero_row(A, temp_row):
                temp_row -= 1
            if temp_row == row:
                return A
            else:
                A = row_interchange(A, row, temp_row)
        # 1. locate the leftmost non-zero column
        while(is_zero_column(A, row, column)): # move to the next column if current column is zero-column
            column += 1
        if column == len(A[0]-1):
            return A
        for i in range(row, len(A)):
            if not A[i][column] == 0:
                A = row_interchange(A, row, i) # 2. interchange
                
                print(f"Interchange row {row} with row {i} \n", A)
                
                break
        # 3. multiply the top row by 1/a
        alpha = A[row][column]
        A = row_scalar_multiply(A, row, 1/alpha)
        
        print(f"Multiply row {row} with 1/{alpha} \n", A)
        
        # 4. multiply the top row with a suitable number
        if not(row == len(A)-1):
            for i in range (row+1, len(A)):
                if not A[i][column] == 0:
                    alpha = A[i][column]
                    B = row_addition(row_scalar_multiply(A, row, -1*alpha), row, i)
                    A = row_scalar_multiply(B, row, -1/alpha)
                    
            print(f"Multiply the row {row} with a suitable numebr and addd it to other", \
            "below rows so that all other elements of the current column is 0 \n", A) 
            
        # 6. Recursion        
        return forward(A, row+1, column+1)

In [144]:
def backward(A, row):
    # base case
    if row == -1:
        print("\nDONE\n", A)
        return A
    # recursive case
    else:
        column = -1
        for i in range(len(A[0])):
            if A[row][i] == 1:
                column = i
                break
        if row > 0:
            for i in range(row-1, -1, -1):
                alpha = A[i][column]
                B = row_addition(row_scalar_multiply(A, row, -1*alpha), row, i)
                A = row_scalar_multiply(B, row, -1/alpha)
        print(f"Row {row} \n", A)
        return backward(A, row-1)

In [145]:
def row_interchange(A, row1, row2):
    """
    Interchange 2 rows (row1 and row2) of matrix A
    Return the updated matrix
    """
    A[[row1, row2]] = A[[row2, row1]]
    return A

def row_scalar_multiply(A, row, alpha):
    """
    Multiply all entries in row of matrix A with scalar alpha
    Return the updated matrix
    """
    A[row] = A[row]*alpha
    return A
    
def row_addition(A, row1, row2):
    """
    Add entry-wisely row1 to row2 of matrix A
    Return the updated matrix
    """
    A[row2] = A[row1] + A[row2]
    return A
    
def is_zero_row(A, row):
    """
    Check if row of matrix A is a zero-row. 
    Return True if it is, else otherwise
    """
    return np.sum(A[row]**2) == 0

def is_zero_column(A, row, column):
    """
    Check if sub column below row of matrix A is a zero sub column
    Return True if it is, else otherwise
    """
    return np.sum(A[row:,column]**2) == 0

# Test routines
A = [[0, 0, -2, 0, 7, 12, 0],
     [2, 4, 0, 6, 12, 28, 0],
     [2, 4, 0,6, -5, -1, 0],
     [0, 0, 0, 0, 0, 0, 0]]

A = np.array(A)
print(A)
B = A.copy()
print("Interchange row 0 and 1 \n", row_interchange(B, 0, 1))
B = A.copy()
print("Multiply row 1 with 2 \n", row_scalar_multiply(B, 1, 2))
B = A.copy()
print("Add row 1 and 2 to row 2 \n", row_addition(B, 1, 2))

print(is_zero_row(A,-1))
print(is_zero_column(A,2,2))

[[ 0  0 -2  0  7 12  0]
 [ 2  4  0  6 12 28  0]
 [ 2  4  0  6 -5 -1  0]
 [ 0  0  0  0  0  0  0]]
Interchange row 0 and 1 
 [[ 2  4  0  6 12 28  0]
 [ 0  0 -2  0  7 12  0]
 [ 2  4  0  6 -5 -1  0]
 [ 0  0  0  0  0  0  0]]
Multiply row 1 with 2 
 [[ 0  0 -2  0  7 12  0]
 [ 4  8  0 12 24 56  0]
 [ 2  4  0  6 -5 -1  0]
 [ 0  0  0  0  0  0  0]]
Add row 1 and 2 to row 2 
 [[ 0  0 -2  0  7 12  0]
 [ 2  4  0  6 12 28  0]
 [ 4  8  0 12  7 27  0]
 [ 0  0  0  0  0  0  0]]
True
True


In [146]:
A = [[0, 0, -2, 0, 7, 12],
     [2, 4, -10, 6, 12, 28],
     [2, 4, -5,6, -5, -1]]
A = np.array(A, dtype = np.float64)
print("Gaussian-Jordan elimination on matrix\n", A)
print("Forward step")
A = forward(A, 0, 0)
print("Backward step")
backward(A, len(A)-1)

Gaussian-Jordan elimination on matrix
 [[  0.   0.  -2.   0.   7.  12.]
 [  2.   4. -10.   6.  12.  28.]
 [  2.   4.  -5.   6.  -5.  -1.]]
Forward step
Interchange row 0 with row 1 
 [[  2.   4. -10.   6.  12.  28.]
 [  0.   0.  -2.   0.   7.  12.]
 [  2.   4.  -5.   6.  -5.  -1.]]
Multiply row 0 with 1/2.0 
 [[ 1.  2. -5.  3.  6. 14.]
 [ 0.  0. -2.  0.  7. 12.]
 [ 2.  4. -5.  6. -5. -1.]]
Multiply the row 0 with a suitable numebr and addd it to other below rows so that all other elements of the current column is 0 
 [[  1.   2.  -5.   3.   6.  14.]
 [  0.   0.  -2.   0.   7.  12.]
 [  0.   0.   5.   0. -17. -29.]]
Interchange row 1 with row 1 
 [[  1.   2.  -5.   3.   6.  14.]
 [  0.   0.  -2.   0.   7.  12.]
 [  0.   0.   5.   0. -17. -29.]]
Multiply row 1 with 1/-2.0 
 [[  1.    2.   -5.    3.    6.   14. ]
 [ -0.   -0.    1.   -0.   -3.5  -6. ]
 [  0.    0.    5.    0.  -17.  -29. ]]
Multiply the row 1 with a suitable numebr and addd it to other below rows so that all other element

array([[1., 2., 0., 3., 0., 7.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1., 2.]])

In [147]:
A_true = [[1, 2, -5, 3, 6, 14],
          [0, 0, 1, 0, -7/2, -6],
          [0, 0, 0, 0, 1, 2]]

A_true = np.array(A_true, dtype = np.float16)